import {
  Chrome, BookOpen, Users, ListChecks, Box, MapPin, FileText, Brain,
  GraduationCap, Leaf, CalendarDays, Receipt, UtensilsCrossed, PawPrint,
  Clock, Mail, QrCode, Mic, Building2, CreditCard, MessageSquareHeart,
  Briefcase, BookOpenCheck, Wallet, FileCode,
  type LucideIcon
} from "lucide-react";

export type ProjectStatus = "launched" | "in-progress" | "upcoming";

export interface Project {
  id: string;
  number: number;
  title: string;
  description: string;
  imageUrl: string;
  projectPageUrl: string;
  type: string;
  status: ProjectStatus;
  icon: LucideIcon;
  features: { title: string; description: string }[];
  techStack: string[];
  keyLearnings: string[];
  ctaText: string;
  heroSubtitle: string;
}

export const projects: Project[] = [
  {
    id: "daily-affirmations",
    number: 1,
    title: "Daily Affirmations",
    description:
      "Transform your new tab into a daily source of inspiration with beautiful affirmations and customizable themes.",
    imageUrl: "/palm-leaf.png",
    projectPageUrl: "/projects/daily-affirmations",
    type: "Chrome Extension",
    status: "launched",
    icon: Chrome,
    features: [
      { title: "Daily Inspiration", description: "Curated affirmations that inspire and motivate you every day" },
      { title: "Weather Widget", description: "Stay informed with a beautiful, draggable weather display" },
      { title: "Smart Reminders", description: "Set custom reminders to keep your positive mindset" },
      { title: "Customizable Themes", description: "Personalize your experience with beautiful themes and backgrounds" },
      { title: "Premium Features", description: "Unlock advanced features like custom affirmations and cloud sync" },
    ],
    techStack: ["Manifest V3", "TypeScript", "Tailwind CSS", "Chrome Storage API", "Weather API", "Service Workers"],
    keyLearnings: [
      "Implementing Chrome's Manifest V3 architecture",
      "Building performant service workers",
      "Creating draggable UI components",
      "Managing local and cloud storage sync",
    ],
    ctaText: "Add to Chrome",
    heroSubtitle: "Transform your new tab into a daily source of inspiration with our beautiful, customizable Chrome extension.",
  },
  {
    id: "ai-story-generator-kids",
    number: 2,
    title: "AI Story Generator for Kids",
    description:
      "Create magical, personalized bedtime stories with AI assistance tailored to your child's interests.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-story-generator-kids",
    type: "Creative AI Tool",
    status: "launched",
    icon: BookOpen,
    features: [
      { title: "Personalized Characters", description: "Make your child the star of their own story" },
      { title: "Choose Interests & Themes", description: "Select from dinosaurs, space, magic, friendship, and more" },
      { title: "Unique AI Content", description: "Every story is crafted by AI, ensuring a fresh adventure each time" },
      { title: "Age-Appropriate Language", description: "Stories tailored for different age groups" },
      { title: "Save & Print Stories", description: "Keep your favorite stories to read again and again" },
    ],
    techStack: ["React/Next.js", "Tailwind CSS", "Python/Flask", "OpenAI API", "Supabase", "Vercel"],
    keyLearnings: [
      "Prompt engineering for creative AI text generation",
      "Designing for a young audience (UI/UX)",
      "Content filtering and safety for AI-generated content",
      "Managing costs of LLM API calls",
    ],
    ctaText: "Create a Story Now",
    heroSubtitle: "Unlock a world of imagination! Create unique, AI-generated stories for your child.",
  },
  {
    id: "niche-community-forum-builder",
    number: 3,
    title: "Niche Community Forum Builder",
    description:
      "Launch your own vibrant online forum for any passion, profession, or local group. Simple to set up, powerful to manage.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/niche-community-forum-builder",
    type: "SaaS Platform",
    status: "launched",
    icon: Users,
    features: [
      { title: "Easy User Management", description: "Intuitive tools for member registration, roles, and moderation" },
      { title: "Customizable Categories", description: "Organize discussions with flexible categories and tagging" },
      { title: "Simple Theming", description: "Customize the look and feel to match your community's brand" },
      { title: "Moderation Tools", description: "Content flagging, keyword filters, and user warnings/bans" },
      { title: "Rich Discussions", description: "Rich text, image/video embeds, polls, and private messaging" },
    ],
    techStack: ["React/Next.js", "Node.js", "PostgreSQL", "Tailwind CSS", "Pusher", "Redis", "Docker"],
    keyLearnings: [
      "Building multi-tenant architectures",
      "Designing robust user permission systems",
      "Implementing real-time communication features",
      "Community management best practices",
    ],
    ctaText: "Create Your Forum Free",
    heroSubtitle: "Launch your own vibrant online forum for any passion, profession, or local group.",
  },
  {
    id: "personalized-habit-tracker",
    number: 4,
    title: "Personalized Habit Tracker",
    description:
      "Build lasting positive habits and achieve your personal goals with an intelligent tracker and AI-powered motivational coach.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/personalized-habit-tracker",
    type: "Mobile Web App",
    status: "launched",
    icon: ListChecks,
    features: [
      { title: "Easy Habit Logging", description: "Quickly log your daily habits with a simple and intuitive interface" },
      { title: "Smart Reminders", description: "Set customizable reminders to stay on track throughout your day" },
      { title: "Progress Visualization", description: "Track your streaks and see progress over time with charts" },
      { title: "AI-Powered Insights", description: "Get personalized tips and motivation from our AI coach" },
      { title: "Motivational Messages", description: "Receive daily affirmations and quotes to keep you inspired" },
    ],
    techStack: ["React/Next.js (PWA)", "Tailwind CSS", "Firebase", "Node.js", "Push Notifications API"],
    keyLearnings: [
      "Designing for mobile-first user experience",
      "Implementing effective notification strategies",
      "Leveraging browser storage for offline capabilities (PWA)",
      "Integrating simple AI for personalized feedback",
    ],
    ctaText: "Start Tracking Free",
    heroSubtitle: "Build lasting positive habits and achieve your personal goals with our intelligent tracker.",
  },
  {
    id: "subscription-box-discovery",
    number: 5,
    title: "Subscription Box Discovery",
    description:
      "Explore hundreds of unique subscription boxes tailored to your interests. Filter by category, price, and read real reviews.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/subscription-box-discovery",
    type: "Discovery Platform",
    status: "launched",
    icon: Box,
    features: [
      { title: "Advanced Search & Filters", description: "Narrow down by category, price range, and shipping location" },
      { title: "Curated Collections", description: "Hand-picked collections for various interests" },
      { title: "User Reviews & Ratings", description: "Read authentic reviews from other subscribers" },
      { title: "Exclusive Deals & Coupons", description: "Access special discounts for featured boxes" },
      { title: "Personalized Wishlist", description: "Save your favorite boxes and get notified of deals" },
    ],
    techStack: ["Next.js/React", "Tailwind CSS", "Algolia", "Supabase", "Node.js", "Vercel"],
    keyLearnings: [
      "Designing effective search and filtering UX",
      "Managing and categorizing large product datasets",
      "Implementing affiliate marketing models",
      "Building trust through transparent reviews",
    ],
    ctaText: "Discover Boxes Now",
    heroSubtitle: "Explore hundreds of unique subscription boxes tailored to your interests.",
  },
  {
    id: "local-event-aggregator",
    number: 6,
    title: "Local Event Aggregator",
    description:
      "Discover the best local events, from concerts and workshops to meetups and markets. Never miss out on what's happening nearby.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/local-event-aggregator",
    type: "Community Platform",
    status: "launched",
    icon: MapPin,
    features: [
      { title: "Comprehensive Search", description: "Find events by date, category, location, or keyword" },
      { title: "Up-to-Date Listings", description: "Aggregated events from multiple sources" },
      { title: "Community Submissions", description: "Local organizers can submit their events" },
      { title: "Weekly Newsletter", description: "Curated list of the week's top events" },
      { title: "Featured Events & Venues", description: "Discover highlighted events and popular venues" },
    ],
    techStack: ["Next.js/React", "Tailwind CSS", "Mapbox/Leaflet", "Node.js/Python", "PostgreSQL/PostGIS", "SendGrid"],
    keyLearnings: [
      "Aggregating data from diverse online sources",
      "Geospatial data management and search",
      "Building newsletter subscription systems",
      "Designing for local discovery",
    ],
    ctaText: "Find Events Near You",
    heroSubtitle: "Discover the best local events. Never miss out on what's happening in your area!",
  },
  {
    id: "ai-resume-builder",
    number: 7,
    title: "AI Resume Builder",
    description:
      "Craft a compelling, ATS-friendly resume that gets noticed. AI guides you through content, keywords, and formatting.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-resume-builder",
    type: "Career Tool",
    status: "launched",
    icon: FileText,
    features: [
      { title: "AI Content Suggestions", description: "Get AI-generated bullet points and summaries" },
      { title: "ATS Optimization", description: "Ensure your resume passes Applicant Tracking Systems" },
      { title: "Professional Templates", description: "Modern, recruiter-approved resume templates" },
      { title: "Instant AI Review", description: "Feedback on clarity, impact, and ATS compatibility" },
      { title: "Easy Export", description: "Download in PDF and DOCX formats" },
    ],
    techStack: ["React/Next.js", "Tailwind CSS", "Python/Flask", "OpenAI API", "PDFLib", "Supabase"],
    keyLearnings: [
      "Integrating LLMs for content generation and analysis",
      "Understanding ATS algorithms and resume best practices",
      "Handling PDF generation and formatting",
      "Balancing free/paid features in a career tool",
    ],
    ctaText: "Build Your Resume Now",
    heroSubtitle: "Craft a compelling, ATS-friendly resume that gets noticed with AI assistance.",
  },
  {
    id: "ai-content-generator",
    number: 8,
    title: "AI Content Generator",
    description:
      "Effortlessly generate high-quality blog posts, articles, social media updates, and more with AI-powered content creation.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-content-generator",
    type: "Web Application",
    status: "launched",
    icon: Brain,
    features: [
      { title: "Multiple Content Types", description: "Blog posts, ad copy, email subject lines, and more" },
      { title: "Fast & Efficient", description: "Create high-quality content in minutes, not hours" },
      { title: "Tone & Style Customization", description: "Adjust tone and style to match your brand" },
      { title: "Multilingual Support", description: "Generate content in multiple languages" },
      { title: "Advanced Editing", description: "Refine AI-generated content with built-in editor" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Python/FastAPI", "OpenAI API", "Stripe", "Vercel"],
    keyLearnings: [
      "Integrating with large language models (LLMs)",
      "Designing intuitive UI for AI tools",
      "Managing API costs and usage quotas",
      "Developing a scalable freemium model",
    ],
    ctaText: "Get Started Free",
    heroSubtitle: "Effortlessly generate high-quality content with our cutting-edge AI tool.",
  },
  {
    id: "niche-course-platform-builder",
    number: 9,
    title: "Niche Course Platform Builder",
    description:
      "Empower yourself to teach online! Simple to create, market, and sell your unique courses to a dedicated audience.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/niche-course-platform-builder",
    type: "Creator SaaS",
    status: "launched",
    icon: GraduationCap,
    features: [
      { title: "Intuitive Course Builder", description: "Drag-and-drop interface for videos, PDFs, quizzes, and text" },
      { title: "Student Management", description: "Track progress, manage enrollments, and communicate" },
      { title: "Integrated Payments", description: "Stripe/PayPal for one-time or subscription payments" },
      { title: "Customizable Pages", description: "Beautiful, branded landing pages for your courses" },
      { title: "Sales & Analytics", description: "Monitor sales, revenue, and student engagement" },
    ],
    techStack: ["Next.js/React", "Tailwind CSS", "Node.js/Express", "PostgreSQL", "Stripe API", "Vimeo API"],
    keyLearnings: [
      "Building a multi-tenant SaaS application",
      "Integrating with payment gateways securely",
      "Designing flexible course structures",
      "Video processing and hosting considerations",
    ],
    ctaText: "Start Building Your Course",
    heroSubtitle: "Empower yourself to teach online with our simple yet powerful course platform.",
  },
  {
    id: "smart-plant-care-assistant",
    number: 10,
    title: "Smart Plant Care Assistant",
    description:
      "Get personalized care schedules, timely reminders, AI-powered diagnostics, and identify plants with ease.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/smart-plant-care-assistant",
    type: "Utility Web App",
    status: "launched",
    icon: Leaf,
    features: [
      { title: "Plant Identification", description: "Upload a photo and let AI help identify your plants" },
      { title: "Personalized Schedules", description: "Custom watering, fertilizing, and misting schedules" },
      { title: "Timely Reminders", description: "Never forget to water again with convenient reminders" },
      { title: "AI Plant Doctor", description: "Get AI-powered diagnostics and care advice" },
      { title: "Light & Placement Tips", description: "Learn the best lighting conditions for your plants" },
    ],
    techStack: ["React/Next.js (PWA)", "Tailwind CSS", "Firebase/Supabase", "Python/Flask", "TensorFlow Lite", "Push API"],
    keyLearnings: [
      "Building image recognition models",
      "Developing scheduling and reminder systems",
      "Creating user-friendly collection management UI",
      "Integrating AI for diagnostic purposes",
    ],
    ctaText: "Get Started Free",
    heroSubtitle: "Bring your houseplants to life with personalized AI-powered plant care.",
  },
  {
    id: "social-media-scheduler",
    number: 11,
    title: "Social Media Post Scheduler",
    description:
      "Plan, schedule, and auto-publish posts across multiple social platforms from one simple dashboard.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/social-media-scheduler",
    type: "Marketing Tool",
    status: "in-progress",
    icon: CalendarDays,
    features: [
      { title: "Multi-Platform Publishing", description: "Schedule posts to Twitter/X, LinkedIn, Instagram, and Facebook" },
      { title: "Content Calendar", description: "Visualize your posting schedule with an intuitive drag-and-drop calendar" },
      { title: "AI Caption Writer", description: "Generate engaging captions and hashtags with AI" },
      { title: "Analytics Dashboard", description: "Track engagement, reach, and best posting times" },
      { title: "Team Collaboration", description: "Approve workflows and shared content libraries for teams" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Node.js", "Redis (job queues)", "OAuth 2.0", "Vercel"],
    keyLearnings: [
      "Working with multiple social media APIs and OAuth flows",
      "Building reliable job scheduling and queue systems",
      "Designing intuitive calendar-based interfaces",
      "Handling rate limits and API quotas across platforms",
    ],
    ctaText: "Schedule Your First Post",
    heroSubtitle: "Plan, schedule, and auto-publish across all your social channels from one dashboard.",
  },
  {
    id: "invoice-billing-manager",
    number: 12,
    title: "Invoice & Billing Manager",
    description:
      "Create professional invoices, track payments, and manage your freelance or small business finances effortlessly.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/invoice-billing-manager",
    type: "Finance Tool",
    status: "in-progress",
    icon: Receipt,
    features: [
      { title: "Professional Invoices", description: "Create branded invoices with customizable templates in seconds" },
      { title: "Payment Tracking", description: "Track paid, pending, and overdue invoices at a glance" },
      { title: "Recurring Billing", description: "Set up automatic recurring invoices for retainer clients" },
      { title: "Expense Logging", description: "Log business expenses and attach receipts" },
      { title: "Tax Reports", description: "Generate quarterly and annual summaries for tax filing" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Stripe", "React-PDF", "Vercel"],
    keyLearnings: [
      "PDF generation and email delivery of invoices",
      "Implementing Stripe for online payments",
      "Building financial dashboards with real-time data",
      "Data privacy and security for financial information",
    ],
    ctaText: "Create Your First Invoice",
    heroSubtitle: "Professional invoicing and billing for freelancers and small businesses.",
  },
  {
    id: "ai-meal-planner",
    number: 13,
    title: "AI Meal Planner",
    description:
      "Get personalized weekly meal plans based on your dietary preferences, allergies, and fitness goals — all powered by AI.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-meal-planner",
    type: "Health & Wellness",
    status: "in-progress",
    icon: UtensilsCrossed,
    features: [
      { title: "Personalized Meal Plans", description: "AI-generated weekly menus tailored to your diet and preferences" },
      { title: "Smart Grocery Lists", description: "Auto-generated shopping lists organized by store aisle" },
      { title: "Nutrition Tracking", description: "Calorie and macro breakdowns for every meal" },
      { title: "Recipe Library", description: "Thousands of recipes with step-by-step instructions" },
      { title: "Dietary Filters", description: "Vegan, keto, gluten-free, and allergy-safe options" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "OpenAI API", "Supabase", "Edamam API", "Vercel"],
    keyLearnings: [
      "AI prompt design for nutrition-aware recipe generation",
      "Working with food and nutrition databases",
      "Building preference engines and recommendation systems",
      "Handling complex dietary constraint logic",
    ],
    ctaText: "Plan Your Meals",
    heroSubtitle: "Personalized weekly meal plans powered by AI, tailored to your goals.",
  },
  {
    id: "pet-care-tracker",
    number: 14,
    title: "Pet Care Tracker",
    description:
      "Keep track of your pet's health, vet visits, medications, feeding schedules, and milestones in one place.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/pet-care-tracker",
    type: "Lifestyle App",
    status: "upcoming",
    icon: PawPrint,
    features: [
      { title: "Health Records", description: "Store vet visits, vaccinations, and medical history digitally" },
      { title: "Medication Reminders", description: "Never miss a dose with smart medication alerts" },
      { title: "Feeding Schedules", description: "Track meals, portions, and dietary needs" },
      { title: "Growth Milestones", description: "Photo journal and milestone tracking for your pet" },
      { title: "Multi-Pet Support", description: "Manage all your pets from a single dashboard" },
    ],
    techStack: ["Next.js (PWA)", "TypeScript", "Tailwind CSS", "Firebase", "Cloud Messaging", "Vercel"],
    keyLearnings: [
      "Building progressive web apps with offline support",
      "Implementing complex scheduling and reminder systems",
      "Designing multi-entity data models",
      "Photo storage and gallery management",
    ],
    ctaText: "Track Your Pet's Health",
    heroSubtitle: "All your pet's health, feeding, and vet records in one beautiful app.",
  },
  {
    id: "freelancer-time-tracker",
    number: 15,
    title: "Freelancer Time Tracker",
    description:
      "Track billable hours, manage projects, and generate detailed time reports for your freelance clients.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/freelancer-time-tracker",
    type: "Productivity Tool",
    status: "upcoming",
    icon: Clock,
    features: [
      { title: "One-Click Timer", description: "Start and stop timers with a single click from any device" },
      { title: "Project & Client Management", description: "Organize time entries by project and client" },
      { title: "Detailed Reports", description: "Generate invoiceable time reports with exports" },
      { title: "Hourly Rate Calculator", description: "Set different rates per project or client" },
      { title: "Weekly Summaries", description: "Automatic weekly digests of your tracked time" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Chart.js", "React-PDF", "Vercel"],
    keyLearnings: [
      "Building real-time timer components with state persistence",
      "Designing flexible reporting and export systems",
      "Multi-timezone handling for international clients",
      "Integrating time data with invoicing workflows",
    ],
    ctaText: "Start Tracking Time",
    heroSubtitle: "Track billable hours, manage projects, and generate reports for your freelance business.",
  },
  {
    id: "email-signature-generator",
    number: 16,
    title: "Email Signature Generator",
    description:
      "Create professional, branded email signatures in minutes with customizable templates and one-click install.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/email-signature-generator",
    type: "Business Tool",
    status: "upcoming",
    icon: Mail,
    features: [
      { title: "Professional Templates", description: "Choose from dozens of modern, mobile-friendly designs" },
      { title: "Brand Customization", description: "Match your company colors, fonts, and logo" },
      { title: "Social Icons", description: "Add links to all your social profiles and CTAs" },
      { title: "One-Click Install", description: "Easy setup guides for Gmail, Outlook, and Apple Mail" },
      { title: "Team Management", description: "Create consistent signatures for your entire team" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "HTML Email Templates", "Supabase", "Vercel"],
    keyLearnings: [
      "Building HTML email-compatible components",
      "Cross-client email rendering challenges",
      "Real-time visual editors with live preview",
      "Generating copy-paste-ready HTML snippets",
    ],
    ctaText: "Create Your Signature",
    heroSubtitle: "Professional email signatures in minutes with customizable templates.",
  },
  {
    id: "qr-code-menu-builder",
    number: 17,
    title: "QR Code Menu Builder",
    description:
      "Build beautiful digital menus for restaurants and cafes. Customers scan a QR code to see your menu on their phone.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/qr-code-menu-builder",
    type: "Restaurant Tech",
    status: "upcoming",
    icon: QrCode,
    features: [
      { title: "Drag & Drop Menu Builder", description: "Easily create and organize menu categories and items" },
      { title: "Auto QR Code Generation", description: "Get a unique QR code for each menu" },
      { title: "Photo Uploads", description: "Add mouth-watering photos to your menu items" },
      { title: "Real-Time Updates", description: "Change prices or items instantly — no reprinting" },
      { title: "Multi-Language Support", description: "Serve international customers with translated menus" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "qrcode.js", "Cloudinary", "Vercel"],
    keyLearnings: [
      "QR code generation and dynamic linking",
      "Building real-time editable content systems",
      "Image optimization for mobile-first experiences",
      "Multi-tenancy for restaurant clients",
    ],
    ctaText: "Build Your Digital Menu",
    heroSubtitle: "Beautiful digital menus that customers access with a simple QR code scan.",
  },
  {
    id: "podcast-show-notes-generator",
    number: 18,
    title: "Podcast Show Notes Generator",
    description:
      "Upload your podcast episode and let AI generate professional show notes, timestamps, and social media snippets.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/podcast-show-notes-generator",
    type: "Creator Tool",
    status: "upcoming",
    icon: Mic,
    features: [
      { title: "AI Transcription", description: "Automatic speech-to-text transcription of episodes" },
      { title: "Smart Show Notes", description: "AI-generated structured summaries with key takeaways" },
      { title: "Timestamp Generation", description: "Automatic chapter markers and timestamps" },
      { title: "Social Snippets", description: "Ready-to-post quotes and highlights for social media" },
      { title: "SEO Blog Posts", description: "Convert episodes into SEO-optimized blog articles" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Whisper API", "OpenAI API", "FFmpeg", "Vercel"],
    keyLearnings: [
      "Audio processing and transcription pipelines",
      "AI summarization and content extraction",
      "Handling large file uploads and processing",
      "Building creator-focused workflow tools",
    ],
    ctaText: "Generate Show Notes",
    heroSubtitle: "Upload your episode and let AI create show notes, timestamps, and social snippets.",
  },
  {
    id: "landlord-tenant-portal",
    number: 19,
    title: "Landlord-Tenant Portal",
    description:
      "Simplify property management with a portal for rent collection, maintenance requests, and lease management.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/landlord-tenant-portal",
    type: "Property Management",
    status: "upcoming",
    icon: Building2,
    features: [
      { title: "Online Rent Collection", description: "Tenants pay rent online with automatic reminders" },
      { title: "Maintenance Requests", description: "Submit, track, and resolve maintenance issues" },
      { title: "Lease Management", description: "Store leases digitally with e-signature support" },
      { title: "Expense Tracking", description: "Track property expenses and generate financial reports" },
      { title: "Tenant Screening", description: "Background and credit check integrations" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Stripe", "DocuSign API", "Vercel"],
    keyLearnings: [
      "Building multi-role access control systems",
      "Integrating payment and document signing APIs",
      "Designing workflows for property management",
      "Handling sensitive financial and personal data",
    ],
    ctaText: "Manage Your Properties",
    heroSubtitle: "Simplify rent collection, maintenance, and lease management in one portal.",
  },
  {
    id: "digital-business-card",
    number: 20,
    title: "Digital Business Card Maker",
    description:
      "Create a sleek digital business card with your info, socials, and portfolio link — shareable via QR code or URL.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/digital-business-card",
    type: "Networking Tool",
    status: "upcoming",
    icon: CreditCard,
    features: [
      { title: "Beautiful Templates", description: "Choose from modern card designs that make an impression" },
      { title: "QR Code Sharing", description: "Share your card instantly with a scannable QR code" },
      { title: "Contact Integration", description: "One-tap save to phone contacts (vCard)" },
      { title: "Analytics", description: "See how many times your card has been viewed and shared" },
      { title: "Custom URL", description: "Get your own branded short link for your card" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "qrcode.js", "vCard.js", "Vercel"],
    keyLearnings: [
      "vCard generation and contact saving",
      "Short URL routing and analytics tracking",
      "Building shareable, SEO-optimized profile pages",
      "QR code integration for physical-to-digital bridges",
    ],
    ctaText: "Create Your Card",
    heroSubtitle: "A sleek digital business card shareable via QR code or custom URL.",
  },
  {
    id: "customer-feedback-widget",
    number: 21,
    title: "Customer Feedback Widget",
    description:
      "Embed a lightweight feedback widget on your website to collect user opinions, bug reports, and feature requests.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/customer-feedback-widget",
    type: "SaaS Tool",
    status: "upcoming",
    icon: MessageSquareHeart,
    features: [
      { title: "Embeddable Widget", description: "Add to any site with a single script tag" },
      { title: "Categorized Feedback", description: "Organize by bugs, features, praise, and questions" },
      { title: "Screenshot Capture", description: "Users can annotate screenshots with their feedback" },
      { title: "Voting & Prioritization", description: "Let users upvote feature requests" },
      { title: "Integrations", description: "Forward feedback to Slack, Linear, or Jira" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Web Components", "Webhooks", "Vercel"],
    keyLearnings: [
      "Building embeddable widgets with Web Components",
      "Cross-origin communication and iframe strategies",
      "Designing lightweight, non-intrusive UI overlays",
      "Building webhook-based integration systems",
    ],
    ctaText: "Add to Your Site",
    heroSubtitle: "Collect user feedback, bug reports, and feature requests with an embeddable widget.",
  },
  {
    id: "micro-job-board",
    number: 22,
    title: "Micro Job Board",
    description:
      "Create a niche job board for a specific industry, skill set, or location. Connecting talent with the right opportunities.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/micro-job-board",
    type: "Marketplace",
    status: "upcoming",
    icon: Briefcase,
    features: [
      { title: "Easy Job Posting", description: "Employers post jobs in minutes with structured forms" },
      { title: "Smart Search", description: "Filter jobs by role, location, salary, and remote options" },
      { title: "Email Alerts", description: "Job seekers get notified of new matching positions" },
      { title: "Company Profiles", description: "Employers showcase their brand and culture" },
      { title: "Paid Listings", description: "Premium placement and featured job options" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Algolia", "Stripe", "Resend", "Vercel"],
    keyLearnings: [
      "Building two-sided marketplace platforms",
      "Full-text search and filtering at scale",
      "Monetization through paid listings and featured posts",
      "Email notification and alert systems",
    ],
    ctaText: "Post a Job",
    heroSubtitle: "A niche job board connecting talent with the right opportunities.",
  },
  {
    id: "study-flashcard-generator",
    number: 23,
    title: "Study Flashcard Generator",
    description:
      "Paste your notes or upload a PDF and let AI create spaced-repetition flashcards to supercharge your studying.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/study-flashcard-generator",
    type: "Education Tool",
    status: "upcoming",
    icon: BookOpenCheck,
    features: [
      { title: "AI Card Generation", description: "Paste notes or upload PDFs and get flashcards instantly" },
      { title: "Spaced Repetition", description: "Science-backed scheduling for optimal retention" },
      { title: "Multiple Card Types", description: "Q&A, cloze deletion, and image-based cards" },
      { title: "Study Analytics", description: "Track your mastery and identify weak spots" },
      { title: "Deck Sharing", description: "Share flashcard decks with classmates" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "OpenAI API", "Supabase", "PDF.js", "Vercel"],
    keyLearnings: [
      "Implementing spaced repetition algorithms (SM-2)",
      "PDF parsing and text extraction",
      "AI-driven content decomposition into Q&A pairs",
      "Gamification and study streak mechanics",
    ],
    ctaText: "Create Flashcards",
    heroSubtitle: "Let AI turn your notes into spaced-repetition flashcards for faster learning.",
  },
  {
    id: "budget-tracker-couples",
    number: 24,
    title: "Budget Tracker for Couples",
    description:
      "Track shared expenses, split bills, and manage household budgets together with your partner in real time.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/budget-tracker-couples",
    type: "Finance App",
    status: "upcoming",
    icon: Wallet,
    features: [
      { title: "Shared Budgets", description: "Create joint budgets with spending limits by category" },
      { title: "Expense Splitting", description: "Track who paid what and settle balances easily" },
      { title: "Real-Time Sync", description: "Both partners see updates instantly" },
      { title: "Savings Goals", description: "Set and track shared savings goals together" },
      { title: "Monthly Reports", description: "Visual spending breakdowns and trend analysis" },
    ],
    techStack: ["Next.js (PWA)", "TypeScript", "Tailwind CSS", "Supabase Realtime", "Chart.js", "Vercel"],
    keyLearnings: [
      "Real-time data synchronization between users",
      "Building collaborative financial tools",
      "Privacy and data sharing between accounts",
      "Designing for couple-specific UX patterns",
    ],
    ctaText: "Start Budgeting Together",
    heroSubtitle: "Track shared expenses and manage household budgets together in real time.",
  },
  {
    id: "changelog-roadmap-builder",
    number: 25,
    title: "Changelog & Roadmap Builder",
    description:
      "Create a beautiful public changelog and product roadmap page for your SaaS. Keep users informed and engaged.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/changelog-roadmap-builder",
    type: "Developer Tool",
    status: "upcoming",
    icon: FileCode,
    features: [
      { title: "Public Changelog", description: "Beautiful, customizable changelog page for your product" },
      { title: "Roadmap Board", description: "Visual kanban-style roadmap with planned/in-progress/done" },
      { title: "Feature Voting", description: "Let users vote on what to build next" },
      { title: "Email Notifications", description: "Notify subscribers when new updates ship" },
      { title: "Custom Domain", description: "Host on your own subdomain (changelog.yoursite.com)" },
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Resend", "Markdown/MDX", "Vercel"],
    keyLearnings: [
      "Building embeddable and standalone page products",
      "Custom domain and subdomain routing",
      "Markdown/MDX rendering for rich content",
      "User voting and prioritization algorithms",
    ],
    ctaText: "Create Your Changelog",
    heroSubtitle: "A beautiful public changelog and roadmap to keep your users informed.",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.id === slug);
}

export function getProjectsByStatus(status: ProjectStatus): Project[] {
  return projects.filter((p) => p.status === status);
}
