import {
  Chrome, PenLine, Mail, Share2, Headset, Video, FileText, GitPullRequest,
  Search, ShoppingBag, Receipt, Eye, Repeat2, UserCheck, Scale, FileSearch,
  PiggyBank, Home, Newspaper, GraduationCap, Star, Mic, Languages,
  Workflow, GitCommit,
  type LucideIcon,
} from "lucide-react";

export type ProjectStatus = "launched" | "in-progress" | "upcoming";

export interface Project {
  id: string;
  number: number;
  title: string;
  tagline: string;
  description: string;
  imageUrl: string;
  projectPageUrl: string;
  type: string;
  status: ProjectStatus;
  icon: LucideIcon;
  pricing: string;
  revenueModel: string;
  monthlyRevenuePotential: string;
  features: { title: string; description: string }[];
  techStack: string[];
  keyLearnings: string[];
  ctaText: string;
  heroSubtitle: string;
  whyItMakesMoney: string;
  buildWeek: string;
  idealCustomer: string;
  competitors: string[];
  useCases: string[];
}

export const projects: Project[] = [
  {
    id: "daily-affirmations",
    number: 1,
    title: "AI Affirmation Engine",
    tagline: "Your new tab, powered by AI-generated positivity",
    description:
      "A Chrome Extension that uses AI to generate personalized, context-aware affirmations based on user mood, goals, and time of day. Premium tier unlocks unlimited AI generations and cloud sync.",
    imageUrl: "/palm-leaf.png",
    projectPageUrl: "/projects/daily-affirmations",
    type: "Chrome Extension",
    status: "launched",
    icon: Chrome,
    pricing: "Free / $4.99/mo Premium",
    revenueModel: "Freemium subscription",
    monthlyRevenuePotential: "$300–$800",
    whyItMakesMoney: "Chrome Extensions have zero distribution cost via the Web Store. Premium tier with AI-personalized affirmations, cloud sync, and custom themes converts 5-8% of free users. At 200 premium users × $4.99 = $998/mo.",
    features: [
      { title: "AI-Personalized Affirmations", description: "GPT-powered affirmations tailored to your current mood, goals, and time of day" },
      { title: "Mood Tracking Agent", description: "An AI agent that learns your patterns and proactively adjusts affirmation tone" },
      { title: "Smart Scheduling", description: "AI determines the best moments to show affirmations based on your browsing habits" },
      { title: "Theme Generation", description: "AI generates unique visual themes and backgrounds that match your affirmation" },
      { title: "Cloud Sync & Cross-Device", description: "Seamlessly sync your preferences, history, and streaks across all devices" },
    ],
    techStack: ["Manifest V3", "TypeScript", "Tailwind CSS", "OpenAI API", "Chrome Storage API", "Service Workers", "Supabase"],
    keyLearnings: [
      "Building Chrome Extensions with Manifest V3",
      "Integrating LLM APIs in browser extensions",
      "Freemium conversion optimization in extensions",
      "Chrome Web Store ASO and distribution",
    ],
    ctaText: "Add to Chrome — It's Free",
    heroSubtitle: "Transform your new tab with AI-generated, personalized affirmations that adapt to your mood and goals.",
    buildWeek: "Week 1–2",
    idealCustomer: "Self-improvement enthusiasts, productivity hackers, and remote workers who spend hours in Chrome daily. They value positive mindset practices but forget to do them consistently.",
    competitors: ["Momentum Dashboard", "Mindful New Tab", "DailyAffirmations.com", "Headspace"],
    useCases: ["Starting the day with a positive mindset", "Replacing doom-scrolling with affirmations", "Tracking mood patterns over time", "Sharing daily affirmations with friends"],
  },
  {
    id: "ai-seo-content-agent",
    number: 2,
    title: "AI SEO Content Agent",
    tagline: "Autonomous blog posts that rank on Google",
    description:
      "An agentic AI that autonomously researches keywords, writes SEO-optimized blog posts, generates images, and publishes directly to your CMS. Set it and let it drive organic traffic.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-seo-content-agent",
    type: "Content Automation",
    status: "launched",
    icon: PenLine,
    pricing: "$49/mo (10 posts) / $99/mo (30 posts)",
    revenueModel: "Tiered subscription",
    monthlyRevenuePotential: "$2,000–$5,000",
    whyItMakesMoney: "Businesses pay $100-500 per SEO article from freelancers. This agent produces them for ~$2 each (API costs). At $49/mo with just 50 customers = $2,450/mo. Content marketing is a $400B industry.",
    features: [
      { title: "Autonomous Keyword Research", description: "Agent analyzes your niche, finds low-competition keywords, and builds a content calendar" },
      { title: "Long-Form Article Generation", description: "Writes 2,000+ word articles with proper H-tags, internal linking, and SEO structure" },
      { title: "AI Image Generation", description: "Generates unique blog images and infographics using DALL-E/Stable Diffusion" },
      { title: "Direct CMS Publishing", description: "Auto-publishes to WordPress, Ghost, Webflow, or Shopify with one click" },
      { title: "Performance Tracking", description: "Monitors rankings, traffic, and suggests content updates when positions drop" },
    ],
    techStack: ["Next.js", "TypeScript", "LangChain", "OpenAI GPT-4", "Serper API", "DALL-E 3", "WordPress REST API", "Supabase", "Stripe"],
    keyLearnings: [
      "Building multi-step agentic AI workflows with LangChain",
      "SEO optimization and keyword research automation",
      "CMS API integrations at scale",
      "Managing LLM costs while maintaining quality",
    ],
    ctaText: "Start Publishing AI Content",
    heroSubtitle: "An AI agent that researches, writes, illustrates, and publishes SEO blog posts — autonomously.",
    buildWeek: "Week 3–4",
    idealCustomer: "Small business owners, SaaS founders, and content marketers who know SEO drives traffic but lack the time or skill to write consistently. They want hands-off content that ranks.",
    competitors: ["Jasper AI", "Surfer SEO", "Writesonic", "SEOwind", "Koala AI"],
    useCases: ["Auto-publishing weekly blog posts for a SaaS blog", "Generating product comparison articles for affiliate sites", "Creating location-based landing pages for local businesses", "Scaling content for a niche authority site"],
  },
  {
    id: "ai-cold-email-agent",
    number: 3,
    title: "AI Cold Outreach Agent",
    tagline: "Personalized sales emails that actually convert",
    description:
      "An AI agent that researches prospects, crafts hyper-personalized cold emails by analyzing their LinkedIn, website, and recent activity, then sends follow-up sequences on autopilot.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-cold-email-agent",
    type: "Sales Automation",
    status: "launched",
    icon: Mail,
    pricing: "$39/mo (500 emails) / $79/mo (2,000 emails)",
    revenueModel: "Usage-based subscription",
    monthlyRevenuePotential: "$3,000–$8,000",
    whyItMakesMoney: "B2B sales teams pay $500-2000/mo for outreach tools. AI personalization 3x reply rates vs. templates. Agency owners and SDRs will pay $39-79/mo happily. 80 customers × $50 avg = $4,000/mo.",
    features: [
      { title: "Prospect Research Agent", description: "Autonomously researches each prospect's company, role, recent news, and interests" },
      { title: "Hyper-Personalized Emails", description: "Crafts unique, context-rich emails that reference real details — not just {firstName}" },
      { title: "Smart Follow-Up Sequences", description: "AI adapts follow-up timing and tone based on open/click signals" },
      { title: "A/B Testing Agent", description: "Automatically tests subject lines and messaging, learns what works for your niche" },
      { title: "CRM Integration", description: "Syncs with HubSpot, Salesforce, Pipedrive, and Google Sheets" },
    ],
    techStack: ["Next.js", "TypeScript", "LangChain Agents", "OpenAI GPT-4", "Resend/SendGrid", "LinkedIn Scraper", "Supabase", "Stripe", "Bull MQ"],
    keyLearnings: [
      "Building autonomous research agents with web scraping",
      "Email deliverability and warm-up strategies",
      "Multi-step agent orchestration with LangChain",
      "B2B SaaS pricing and conversion optimization",
    ],
    ctaText: "Send Your First AI Email",
    heroSubtitle: "AI researches each prospect and writes emails so personalized they feel hand-written.",
    buildWeek: "Week 5–6",
    idealCustomer: "B2B sales teams, agency owners, and solopreneurs who need pipeline but hate writing cold emails. They've tried templates and know personalization wins but can't scale it manually.",
    competitors: ["Instantly.ai", "Lemlist", "Apollo.io", "Smartlead", "Woodpecker"],
    useCases: ["SDRs personalizing 200+ outbound emails per day", "Agency owners pitching potential clients", "SaaS founders reaching out to beta users", "Freelancers finding new clients in a niche"],
  },
  {
    id: "ai-social-autopilot",
    number: 4,
    title: "AI Social Media Autopilot",
    tagline: "Your AI social media manager that never sleeps",
    description:
      "An AI agent that analyzes your brand voice, generates on-brand posts with images, schedules them at optimal times, and even responds to comments — across all platforms.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-social-autopilot",
    type: "Marketing Automation",
    status: "launched",
    icon: Share2,
    pricing: "$29/mo (3 platforms) / $59/mo (unlimited)",
    revenueModel: "Tiered subscription",
    monthlyRevenuePotential: "$2,500–$6,000",
    whyItMakesMoney: "Social media managers charge $500-2000/mo. This AI does 80% of the work for $29/mo. Solopreneurs and small businesses are the perfect market. 100 customers × $35 avg = $3,500/mo.",
    features: [
      { title: "Brand Voice AI", description: "Learns your tone from past posts and maintains consistent voice across all content" },
      { title: "Multi-Platform Agent", description: "Creates and posts to Twitter/X, LinkedIn, Instagram, Facebook, and TikTok" },
      { title: "AI Image & Carousel Generation", description: "Generates custom visuals, carousels, and short video scripts" },
      { title: "Optimal Time Scheduling", description: "AI analyzes your audience activity to post at the highest-engagement windows" },
      { title: "Comment Response Agent", description: "Monitors and responds to comments with on-brand, contextual replies" },
    ],
    techStack: ["Next.js", "TypeScript", "CrewAI", "OpenAI GPT-4", "DALL-E 3", "Twitter API", "LinkedIn API", "Meta API", "Redis", "Stripe"],
    keyLearnings: [
      "Multi-agent systems with CrewAI for social media workflows",
      "OAuth integration with multiple social platforms",
      "Content scheduling and queue management",
      "Brand voice fine-tuning and consistency",
    ],
    ctaText: "Automate Your Social Media",
    heroSubtitle: "An AI agent that creates, posts, and engages across all your social channels — on brand, on time.",
    buildWeek: "Week 7–8",
    idealCustomer: "Solopreneurs, small business owners, and indie hackers who know they need social media presence but can't justify hiring a social media manager. They want consistency without the time investment.",
    competitors: ["Buffer", "Hootsuite", "Later", "Publer", "Typefully"],
    useCases: ["Maintaining a consistent posting schedule across 3+ platforms", "Auto-generating LinkedIn thought leadership content", "Creating Instagram carousels from blog posts", "Monitoring and responding to brand mentions"],
  },
  {
    id: "ai-support-agent",
    number: 5,
    title: "AI Customer Support Agent",
    tagline: "24/7 AI support that resolves 80% of tickets instantly",
    description:
      "A trainable AI agent that learns your product docs, FAQ, and past tickets, then autonomously resolves customer issues via chat, email, or widget — escalating only when needed.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-support-agent",
    type: "Customer Service AI",
    status: "launched",
    icon: Headset,
    pricing: "$49/mo (1,000 resolutions) / $129/mo (unlimited)",
    revenueModel: "Usage-based subscription",
    monthlyRevenuePotential: "$5,000–$15,000",
    whyItMakesMoney: "A single human support agent costs $3,000+/mo. This AI handles 80% of tickets for $49/mo. SaaS companies, e-commerce stores, and agencies are desperate for this. 60 customers × $80 avg = $4,800/mo.",
    features: [
      { title: "Knowledge Base Training", description: "Upload docs, FAQ, or a URL — the agent learns your product in minutes" },
      { title: "Multi-Channel Support", description: "Deploys as a website widget, Slack bot, email responder, or API" },
      { title: "Smart Escalation", description: "Knows when to hand off to a human with full context summary" },
      { title: "Ticket Categorization", description: "Auto-tags, prioritizes, and routes tickets by urgency and topic" },
      { title: "Analytics Dashboard", description: "Resolution rates, CSAT predictions, and knowledge gap reports" },
    ],
    techStack: ["Next.js", "TypeScript", "LangChain", "OpenAI GPT-4", "Pinecone (RAG)", "Supabase", "Stripe", "Web Components", "Webhooks"],
    keyLearnings: [
      "Building RAG pipelines for knowledge-grounded responses",
      "Embeddable widget architecture with Web Components",
      "Conversation state management and context windows",
      "Escalation logic and human-AI handoff patterns",
    ],
    ctaText: "Deploy Your AI Agent",
    heroSubtitle: "A trainable AI agent that resolves customer issues 24/7 — learning from your docs and past tickets.",
    buildWeek: "Week 9–10",
    idealCustomer: "SaaS companies with 100-10,000 customers, e-commerce stores, and developer tool companies that get repetitive support questions and want to provide instant 24/7 resolution without hiring more agents.",
    competitors: ["Intercom Fin", "Zendesk AI", "Freshdesk Freddy", "ChatBot.com", "Tidio"],
    useCases: ["Resolving common 'how to' questions from product docs", "Handling billing and subscription inquiries", "Triaging bug reports and routing to engineering", "Providing instant onboarding help for new users"],
  },
  {
    id: "ai-meeting-copilot",
    number: 6,
    title: "AI Meeting Copilot",
    tagline: "Never take meeting notes again",
    description:
      "An AI agent that joins your Zoom/Google Meet/Teams calls, transcribes everything in real-time, generates structured summaries, extracts action items, and pushes them to your project management tools.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-meeting-copilot",
    type: "Productivity AI",
    status: "launched",
    icon: Video,
    pricing: "$19/mo (20 meetings) / $39/mo (unlimited)",
    revenueModel: "Subscription",
    monthlyRevenuePotential: "$2,000–$5,000",
    whyItMakesMoney: "Professionals waste 31 hours/month in meetings. AI note-taking saves 5+ hours/week. Otter.ai charges $16.99/mo — this offers agentic features (auto-tasks, auto-CRM updates) for $19/mo. 120 users × $25 avg = $3,000/mo.",
    features: [
      { title: "Auto-Join Meetings", description: "Connects to Zoom, Google Meet, and Teams with a calendar integration" },
      { title: "Real-Time Transcription", description: "Speaker-attributed transcription with 95%+ accuracy" },
      { title: "AI Summary Agent", description: "Generates structured summaries with key decisions, action items, and deadlines" },
      { title: "Task Auto-Creation", description: "Pushes action items directly to Linear, Jira, Asana, or Notion" },
      { title: "Meeting Intelligence", description: "Tracks talk-time ratios, sentiment analysis, and follow-up reminders" },
    ],
    techStack: ["Next.js", "TypeScript", "Whisper API", "OpenAI GPT-4", "Zoom SDK", "Google Calendar API", "Supabase", "Stripe", "Bull MQ"],
    keyLearnings: [
      "Audio processing and real-time transcription pipelines",
      "Calendar and meeting platform API integrations",
      "Structured information extraction from unstructured text",
      "Building reliable background job processing",
    ],
    ctaText: "Connect Your Calendar",
    heroSubtitle: "AI that joins your calls, takes perfect notes, and creates tasks in your project tools — automatically.",
    buildWeek: "Week 11–12",
    idealCustomer: "Remote-first teams, sales managers, project managers, and consultants who are in 5+ meetings per day and waste hours on notes. They want structured summaries and automatic task creation.",
    competitors: ["Otter.ai", "Fireflies.ai", "tl;dv", "Fathom", "Grain"],
    useCases: ["Sales teams recording and analyzing discovery calls", "Engineering stand-ups auto-generating Jira tickets", "Consultants sending meeting summaries to clients", "Leadership reviewing meeting talk-time ratios"],
  },
  {
    id: "ai-resume-tailor",
    number: 7,
    title: "AI Resume Tailor Agent",
    tagline: "One resume, tailored to every job in 30 seconds",
    description:
      "Paste a job description and your master resume — the AI agent rewrites your resume to match the role's requirements, optimizes for ATS systems, and generates a matching cover letter.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-resume-tailor",
    type: "Career AI Tool",
    status: "launched",
    icon: FileText,
    pricing: "$9.99/resume or $29/mo unlimited",
    revenueModel: "Pay-per-use + subscription",
    monthlyRevenuePotential: "$1,500–$4,000",
    whyItMakesMoney: "Job seekers apply to 20-50 jobs and need tailored resumes. At $9.99/resume with 150 sales/mo = $1,500. LinkedIn has 600M+ users — this taps into massive demand. Subscription ($29/mo) for active job hunters increases LTV.",
    features: [
      { title: "Job Description Analyzer", description: "AI extracts key requirements, skills, and keywords from any job listing" },
      { title: "Smart Resume Rewriting", description: "Rewrites bullet points to match the role while keeping authenticity" },
      { title: "ATS Score Optimizer", description: "Scores your resume against ATS criteria and fixes issues automatically" },
      { title: "Cover Letter Generator", description: "Creates a tailored cover letter that complements the customized resume" },
      { title: "PDF Export", description: "Professional, clean PDF output ready to submit" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "React-PDF", "Supabase", "Stripe", "Vercel"],
    keyLearnings: [
      "AI-powered document transformation and rewriting",
      "ATS system mechanics and optimization",
      "PDF generation and template rendering",
      "Pay-per-use vs subscription pricing strategies",
    ],
    ctaText: "Tailor Your Resume Now",
    heroSubtitle: "Paste a job description. Get a perfectly tailored resume and cover letter in 30 seconds.",
    buildWeek: "Week 13–14",
    idealCustomer: "Active job seekers applying to 10+ positions per week, career changers, and new graduates who need to customize resumes for each application but lack the time to rewrite everything.",
    competitors: ["Teal", "Jobscan", "Kickresume", "Rezi", "Resume.io"],
    useCases: ["Tailoring a software engineer resume for different tech stacks", "Optimizing a resume for a specific ATS system", "Generating a cover letter matched to the job posting", "Career changers reframing experience for a new industry"],
  },
  {
    id: "ai-code-review-agent",
    number: 8,
    title: "AI Code Review Agent",
    tagline: "Ship better code, faster — with AI PR reviews",
    description:
      "A GitHub-integrated AI agent that reviews every pull request, catches bugs, suggests improvements, identifies security vulnerabilities, and enforces your team's coding standards.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-code-review-agent",
    type: "Developer Tool",
    status: "launched",
    icon: GitPullRequest,
    pricing: "$19/mo per repo / $49/mo for 5 repos",
    revenueModel: "Per-repo subscription",
    monthlyRevenuePotential: "$3,000–$10,000",
    whyItMakesMoney: "Code review is a $2B market bottleneck. Senior dev time costs $100+/hr. This AI reviews PRs in seconds for $19/mo per repo. Dev teams of 3-10 are the sweet spot. 100 repos × $25 avg = $2,500/mo.",
    features: [
      { title: "Automated PR Analysis", description: "Reviews every PR for bugs, performance issues, and anti-patterns" },
      { title: "Security Scanning", description: "Detects vulnerabilities, secrets in code, and dependency issues" },
      { title: "Style Enforcement", description: "Learns your team's coding standards and enforces them consistently" },
      { title: "Inline Suggestions", description: "Posts specific, actionable comments directly on GitHub PR diffs" },
      { title: "Learning Agent", description: "Improves over time based on which suggestions your team accepts" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "GitHub API", "Tree-sitter", "Supabase", "Stripe", "Webhooks"],
    keyLearnings: [
      "GitHub App development and webhook handling",
      "AST analysis and code understanding at scale",
      "Building feedback loops for AI improvement",
      "Developer tool UX and onboarding optimization",
    ],
    ctaText: "Install on GitHub",
    heroSubtitle: "AI agent that reviews every PR — catching bugs, security issues, and enforcing your standards.",
    buildWeek: "Week 15–16",
    idealCustomer: "Engineering teams of 3-20 developers where code review is a bottleneck. Senior devs spend too much time reviewing PRs. They want consistent quality enforcement without slowing down velocity.",
    competitors: ["CodeRabbit", "Sourcery", "DeepCode (Snyk)", "Amazon CodeGuru", "Qodo"],
    useCases: ["Catching security vulnerabilities before merge", "Enforcing team coding standards automatically", "Flagging performance anti-patterns in database queries", "Reviewing dependency updates for breaking changes"],
  },
  {
    id: "ai-lead-scraper",
    number: 9,
    title: "AI Lead Generation Agent",
    tagline: "Find your ideal customers on autopilot",
    description:
      "An AI agent that scrapes the web to find potential customers matching your ICP (ideal customer profile), enriches their data with email/LinkedIn/company info, and scores them by fit.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-lead-scraper",
    type: "Sales Intelligence",
    status: "launched",
    icon: Search,
    pricing: "$39/mo (500 leads) / $99/mo (2,500 leads)",
    revenueModel: "Usage-based subscription",
    monthlyRevenuePotential: "$4,000–$12,000",
    whyItMakesMoney: "Businesses pay $0.10-1.00 per verified lead on platforms like Apollo and ZoomInfo. This agent finds niche leads that those platforms miss. 80 customers × $60 avg = $4,800/mo. Pairs perfectly with the Cold Email Agent.",
    features: [
      { title: "ICP Definition Agent", description: "Define your ideal customer by industry, role, company size, and tech stack" },
      { title: "Multi-Source Scraping", description: "Finds leads from LinkedIn, Google, ProductHunt, GitHub, Twitter/X, and more" },
      { title: "Data Enrichment", description: "Auto-finds verified emails, phone numbers, company revenue, and tech stack" },
      { title: "Lead Scoring", description: "AI scores each lead by how closely they match your ICP" },
      { title: "CRM Export", description: "One-click export to HubSpot, Salesforce, or CSV" },
    ],
    techStack: ["Next.js", "TypeScript", "LangChain Agents", "Playwright", "OpenAI GPT-4", "Hunter.io API", "Supabase", "Stripe", "Bull MQ"],
    keyLearnings: [
      "Ethical web scraping and rate limiting strategies",
      "Data enrichment pipeline architecture",
      "Building configurable AI agents for diverse use cases",
      "Lead scoring algorithms and ICP modeling",
    ],
    ctaText: "Define Your ICP & Go",
    heroSubtitle: "AI agent that finds, enriches, and scores leads matching your ideal customer profile — automatically.",
    buildWeek: "Week 17–18",
    idealCustomer: "B2B sales teams, growth marketers, and agency owners who need a steady stream of qualified leads but find existing databases too broad or too expensive. They want niche-specific, verified leads.",
    competitors: ["Apollo.io", "ZoomInfo", "Lusha", "Hunter.io", "Clearbit"],
    useCases: ["Finding SaaS companies using a specific tech stack", "Building lists of e-commerce stores in a niche", "Identifying recently funded startups for outreach", "Scraping conference attendee lists for follow-up"],
  },
  {
    id: "ai-product-copy-agent",
    number: 10,
    title: "AI Product Copywriter",
    tagline: "E-commerce copy that sells, written by AI",
    description:
      "Upload a product image or URL — the AI agent generates optimized product titles, descriptions, bullet points, SEO meta tags, and ad copy for Amazon, Shopify, Etsy, and more.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-product-copy-agent",
    type: "E-Commerce AI",
    status: "launched",
    icon: ShoppingBag,
    pricing: "$29/mo (100 products) / $69/mo (500 products)",
    revenueModel: "Tiered subscription",
    monthlyRevenuePotential: "$2,000–$6,000",
    whyItMakesMoney: "E-commerce sellers with 100+ products can't manually write copy. Copywriters charge $20-50 per product. This AI does it for ~$0.30/product. Shopify has 4.4M stores. 80 customers × $40 avg = $3,200/mo.",
    features: [
      { title: "Image-to-Copy AI", description: "Upload a product photo and get complete listing copy generated automatically" },
      { title: "Platform-Specific Formats", description: "Optimized copy for Amazon, Shopify, Etsy, eBay, and WooCommerce" },
      { title: "SEO Meta Generation", description: "Auto-generates meta titles, descriptions, and alt tags" },
      { title: "Ad Copy Agent", description: "Creates Facebook, Google, and Instagram ad copy variations" },
      { title: "Bulk Processing", description: "Upload a CSV of products and get all copy generated in one batch" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4 Vision", "DALL-E 3", "Supabase", "Stripe", "Bull MQ", "Vercel"],
    keyLearnings: [
      "Vision-language models for product understanding",
      "E-commerce platform copy requirements and formats",
      "Bulk processing and job queue architecture",
      "Multi-marketplace optimization strategies",
    ],
    ctaText: "Generate Product Copy",
    heroSubtitle: "Upload a product photo. Get SEO-optimized titles, descriptions, and ad copy — instantly.",
    buildWeek: "Week 19–20",
    idealCustomer: "E-commerce sellers with 50+ products on Shopify, Amazon, or Etsy who can't afford to hire copywriters for every listing. Dropshippers and private label sellers are ideal targets.",
    competitors: ["Copy.ai", "Writesonic", "Hypotenuse AI", "Describely", "AdCreative.ai"],
    useCases: ["Generating Amazon FBA product listings at scale", "Creating Shopify product descriptions from supplier photos", "Writing Google Shopping ad copy for 500+ SKUs", "Translating and localizing product copy for international markets"],
  },
  {
    id: "ai-invoice-agent",
    number: 11,
    title: "AI Invoice & Expense Agent",
    tagline: "Receipts in, organized finances out",
    description:
      "Snap photos of receipts or forward emails — the AI agent extracts data, categorizes expenses, matches them to projects, generates invoices, and prepares tax summaries.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-invoice-agent",
    type: "Finance Automation",
    status: "in-progress",
    icon: Receipt,
    pricing: "$19/mo (freelancer) / $39/mo (business)",
    revenueModel: "Tiered subscription",
    monthlyRevenuePotential: "$1,500–$4,000",
    whyItMakesMoney: "53M freelancers in the US alone hate doing bookkeeping. At $19/mo with 100 freelancer customers = $1,900/mo. Receipt scanning + AI categorization + invoice generation = high-value automation they'll pay monthly for.",
    features: [
      { title: "Receipt Scanning Agent", description: "Snap a photo or forward an email — AI extracts all line items, totals, and tax" },
      { title: "Auto-Categorization", description: "Learns your expense categories and assigns them automatically over time" },
      { title: "Invoice Generation", description: "Create professional invoices from tracked time or manual entries" },
      { title: "Tax Summary Reports", description: "Quarterly and annual reports organized by tax category" },
      { title: "Bank Feed Matching", description: "Matches expenses to bank transactions (via Plaid)" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4 Vision", "Plaid API", "React-PDF", "Supabase", "Stripe", "Vercel"],
    keyLearnings: [
      "OCR and vision model receipt extraction",
      "Financial data categorization with AI",
      "Plaid API integration for bank feeds",
      "Building tax-compliant financial reports",
    ],
    ctaText: "Scan Your First Receipt",
    heroSubtitle: "AI agent that turns receipts into organized expenses, invoices, and tax reports — automatically.",
    buildWeek: "Week 21–22",
    idealCustomer: "Freelancers, solo consultants, and micro-agency owners who dread bookkeeping. They want to snap receipts and have expenses auto-categorized — and generate professional invoices without touching spreadsheets.",
    competitors: ["QuickBooks Self-Employed", "FreshBooks", "Wave", "Dext (Receipt Bank)", "Keeper Tax"],
    useCases: ["Freelance designer tracking project expenses by client", "Consultant generating monthly invoices from tracked time", "Small agency preparing quarterly tax summaries", "Digital nomad categorizing multi-currency expenses"],
  },
  {
    id: "ai-competitor-spy",
    number: 12,
    title: "AI Competitor Intelligence Agent",
    tagline: "Know what your competitors do before they do",
    description:
      "An AI agent that continuously monitors your competitors' websites, pricing, features, blog posts, social media, and ads — then delivers weekly intelligence reports with actionable insights.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-competitor-spy",
    type: "Market Intelligence",
    status: "in-progress",
    icon: Eye,
    pricing: "$49/mo (3 competitors) / $99/mo (10 competitors)",
    revenueModel: "Tiered subscription",
    monthlyRevenuePotential: "$3,000–$8,000",
    whyItMakesMoney: "SaaS founders and marketing teams obsess over competitors. Existing tools (Crayon, Klue) charge $10K+/yr for enterprises. This brings AI-powered competitive intelligence to SMBs at $49-99/mo. 60 customers × $65 avg = $3,900/mo.",
    features: [
      { title: "Website Change Detection", description: "Monitors pricing pages, feature lists, and landing pages for any changes" },
      { title: "Content & SEO Tracking", description: "Tracks competitors' blog posts, keywords they're targeting, and backlinks" },
      { title: "Social Media Monitoring", description: "Tracks their social posts, engagement, and ad campaigns" },
      { title: "AI Analysis Reports", description: "Weekly AI-generated reports with insights, threats, and opportunities" },
      { title: "Alert System", description: "Instant Slack/email alerts when competitors make significant changes" },
    ],
    techStack: ["Next.js", "TypeScript", "LangChain Agents", "Playwright", "OpenAI GPT-4", "Supabase", "Resend", "Stripe", "Cron Jobs"],
    keyLearnings: [
      "Web scraping and change detection at scale",
      "AI-powered analysis and report generation",
      "Building reliable monitoring and alerting systems",
      "Competitive intelligence data modeling",
    ],
    ctaText: "Track Your Competitors",
    heroSubtitle: "AI agent that monitors competitors 24/7 and delivers weekly intelligence reports.",
    buildWeek: "Week 23–24",
    idealCustomer: "SaaS founders, product managers, and marketing leads at startups who obsess over competitors but lack the budget for enterprise CI tools. They want automated monitoring, not manual Googling.",
    competitors: ["Crayon", "Klue", "Kompyte", "SimilarWeb", "Visualping"],
    useCases: ["Tracking a competitor's pricing page for changes", "Monitoring competitor blog content strategy", "Getting alerts when competitors launch new features", "Analyzing competitor social media ad campaigns"],
  },
  {
    id: "ai-content-repurposer",
    number: 13,
    title: "AI Content Repurposing Agent",
    tagline: "One piece of content → 10 formats automatically",
    description:
      "Upload a blog post, podcast, or video — the AI agent repurposes it into Twitter threads, LinkedIn posts, email newsletters, Instagram carousels, YouTube Shorts scripts, and more.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-content-repurposer",
    type: "Content Automation",
    status: "in-progress",
    icon: Repeat2,
    pricing: "$24/mo (20 repurposes) / $49/mo (unlimited)",
    revenueModel: "Usage-based subscription",
    monthlyRevenuePotential: "$2,000–$5,000",
    whyItMakesMoney: "Content creators and marketers spend 5+ hours repurposing each piece. This does it in 60 seconds. The 'create once, publish everywhere' problem affects every creator. 100 customers × $30 avg = $3,000/mo.",
    features: [
      { title: "Multi-Format Agent", description: "Transforms one input into 10+ content formats optimized for each platform" },
      { title: "Blog → Social Threads", description: "Extracts key insights and creates engaging Twitter threads and LinkedIn posts" },
      { title: "Podcast → Articles", description: "Transcribes audio and creates SEO blog posts with timestamps" },
      { title: "Video → Shorts Scripts", description: "Identifies viral moments and generates YouTube Shorts/Reels scripts" },
      { title: "Email Newsletter Draft", description: "Converts content into newsletter format with subject lines and CTAs" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "Whisper API", "DALL-E 3", "Supabase", "Stripe", "Bull MQ"],
    keyLearnings: [
      "Multi-modal content processing (text, audio, video)",
      "Platform-specific content optimization rules",
      "Building content transformation pipelines",
      "Creator economy monetization strategies",
    ],
    ctaText: "Repurpose Your Content",
    heroSubtitle: "Upload once. Get Twitter threads, LinkedIn posts, newsletters, and more — instantly.",
    buildWeek: "Week 25–26",
    idealCustomer: "Content creators, YouTubers, podcasters, and B2B marketers who produce long-form content but struggle to distribute it across channels. They want one piece of content turned into ten.",
    competitors: ["Repurpose.io", "Opus Clip", "Castmagic", "ContentFly", "Lately.ai"],
    useCases: ["Turning a 2,000-word blog post into a Twitter thread and LinkedIn post", "Converting a podcast episode into a newsletter and blog article", "Extracting YouTube video highlights as Instagram Reels scripts", "Creating email drip sequences from a webinar recording"],
  },
  {
    id: "ai-recruitment-screener",
    number: 14,
    title: "AI Recruitment Screening Agent",
    tagline: "Screen 100 resumes in 60 seconds",
    description:
      "Upload a job description and a stack of resumes — the AI agent screens, ranks, and shortlists candidates, generates interview questions, and schedules calls with top matches.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-recruitment-screener",
    type: "HR Tech",
    status: "upcoming",
    icon: UserCheck,
    pricing: "$79/mo (5 open roles) / $199/mo (unlimited roles)",
    revenueModel: "Subscription",
    monthlyRevenuePotential: "$4,000–$12,000",
    whyItMakesMoney: "Recruiters spend 23 hours screening resumes per hire. A recruiter costs $4,000-8,000/mo. This AI screens in seconds for $79/mo. Staffing agencies and HR teams are the market. 50 customers × $120 avg = $6,000/mo.",
    features: [
      { title: "Batch Resume Analysis", description: "Upload 100+ resumes and get ranked results in under a minute" },
      { title: "JD-to-Scorecard", description: "AI creates a weighted scoring rubric from the job description" },
      { title: "Candidate Ranking", description: "Scores and ranks candidates with detailed fit explanations" },
      { title: "Interview Question Generator", description: "Creates role-specific interview questions for each shortlisted candidate" },
      { title: "Auto-Scheduling", description: "Emails top candidates with a Calendly link to schedule interviews" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "PDF.js", "Calendly API", "Resend", "Supabase", "Stripe"],
    keyLearnings: [
      "Resume parsing and structured data extraction",
      "AI-based scoring and ranking algorithms",
      "Calendar integration and automated scheduling",
      "Building bias-aware AI screening tools",
    ],
    ctaText: "Screen Your Applicants",
    heroSubtitle: "AI agent that screens, ranks, and shortlists candidates — from 100 resumes to a shortlist in 60 seconds.",
    buildWeek: "Week 27–28",
    idealCustomer: "HR teams at growing startups (50-500 employees), staffing agencies, and hiring managers drowning in resumes. They receive 200+ applications per role and need to shortlist in hours, not days.",
    competitors: ["Lever", "Greenhouse ATS", "HireVue", "Pymetrics", "Ideal (Ceridian)"],
    useCases: ["Screening 300 engineering applicants for a senior role", "Ranking marketing candidates by culture fit + skill match", "Generating interview questions tailored to each shortlisted candidate", "Staffing agency processing bulk applications for multiple clients"],
  },
  {
    id: "ai-contract-analyzer",
    number: 15,
    title: "AI Contract Analyzer",
    tagline: "Understand any contract in 30 seconds",
    description:
      "Upload a contract or legal document — the AI agent highlights risky clauses, summarizes key terms, compares against standard templates, and suggests negotiation points.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-contract-analyzer",
    type: "Legal AI Tool",
    status: "upcoming",
    icon: Scale,
    pricing: "$19/contract or $49/mo unlimited",
    revenueModel: "Pay-per-use + subscription",
    monthlyRevenuePotential: "$2,000–$6,000",
    whyItMakesMoney: "Lawyer reviews cost $200-500 per contract. Freelancers and small businesses sign contracts without understanding them. At $19/contract with 100 reviews/mo = $1,900. Subscription converts power users. 80 × $40 avg = $3,200/mo.",
    features: [
      { title: "Risk Highlighting", description: "AI flags unusual, one-sided, or risky clauses with severity ratings" },
      { title: "Plain English Summary", description: "Converts legalese into clear, readable summaries of key terms" },
      { title: "Template Comparison", description: "Compares against industry-standard contract templates" },
      { title: "Negotiation Suggestions", description: "Recommends specific changes and alternative language" },
      { title: "Multi-Format Support", description: "Accepts PDF, DOCX, and even photos of printed contracts" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "PDF.js", "Pinecone (RAG)", "Supabase", "Stripe", "Vercel"],
    keyLearnings: [
      "Legal document understanding with RAG",
      "Risk classification and scoring systems",
      "Building domain-specific AI with fine-tuning",
      "Regulatory considerations for legal AI tools",
    ],
    ctaText: "Analyze Your Contract",
    heroSubtitle: "Upload any contract. Get risk analysis, plain-English summary, and negotiation points in 30 seconds.",
    buildWeek: "Week 29–30",
    idealCustomer: "Freelancers, startup founders, and small business owners who sign contracts regularly but can't afford a lawyer for every review. They want to understand what they're signing before it's too late.",
    competitors: ["Ironclad", "ContractPodAi", "LawGeex", "SpotDraft", "Juro"],
    useCases: ["Freelancer reviewing a client's service agreement", "Startup founder analyzing an investor term sheet", "Small business owner checking a commercial lease", "Agency reviewing a vendor SLA for hidden penalties"],
  },
  {
    id: "ai-data-extractor",
    number: 16,
    title: "AI Data Extraction Agent",
    tagline: "Turn any document into structured data",
    description:
      "Upload PDFs, invoices, forms, or images — the AI agent extracts structured data into spreadsheets, databases, or APIs. Perfect for processing documents at scale.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-data-extractor",
    type: "Data Automation",
    status: "upcoming",
    icon: FileSearch,
    pricing: "$24/mo (500 pages) / $59/mo (2,500 pages)",
    revenueModel: "Usage-based subscription",
    monthlyRevenuePotential: "$2,000–$5,000",
    whyItMakesMoney: "Manual data entry costs businesses $30K+/yr. OCR alone isn't enough — AI understands context. Accounting firms, insurance companies, and logistics companies process thousands of documents. 80 customers × $35 avg = $2,800/mo.",
    features: [
      { title: "Intelligent Document Parsing", description: "Understands invoices, receipts, forms, tables, and handwriting" },
      { title: "Custom Field Mapping", description: "Define which fields to extract and the agent learns your document layout" },
      { title: "Batch Processing", description: "Upload hundreds of documents and process them in parallel" },
      { title: "Export Anywhere", description: "Output to CSV, JSON, Google Sheets, Airtable, or webhook" },
      { title: "Accuracy Verification", description: "Confidence scoring with human-in-the-loop review for low-confidence extractions" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4 Vision", "Tesseract.js", "Bull MQ", "Supabase", "Stripe", "Google Sheets API"],
    keyLearnings: [
      "Vision models for document understanding",
      "Building human-in-the-loop verification workflows",
      "Batch processing architecture with job queues",
      "Enterprise data pipeline design",
    ],
    ctaText: "Extract Your Data",
    heroSubtitle: "AI agent that turns any document into clean, structured data — invoices, forms, receipts, and more.",
    buildWeek: "Week 31–32",
    idealCustomer: "Operations teams, accounting firms, insurance companies, and logistics businesses that process hundreds of paper documents or PDFs monthly. Manual data entry is their biggest time sink.",
    competitors: ["Amazon Textract", "Nanonets", "Rossum", "Parseur", "Docsumo"],
    useCases: ["Accounting firm extracting data from 500 client invoices per month", "Insurance company processing claims forms", "Logistics team digitizing shipping manifests", "Real estate firm extracting terms from lease agreements"],
  },
  {
    id: "ai-finance-coach",
    number: 17,
    title: "AI Personal Finance Coach",
    tagline: "Your AI financial advisor for $9.99/mo",
    description:
      "Connect your bank accounts — the AI agent analyzes spending, identifies savings opportunities, suggests budget adjustments, and sends weekly money-saving tips personalized to your habits.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-finance-coach",
    type: "FinTech AI",
    status: "upcoming",
    icon: PiggyBank,
    pricing: "$9.99/mo",
    revenueModel: "Subscription",
    monthlyRevenuePotential: "$2,000–$8,000",
    whyItMakesMoney: "Financial advisors charge $200+/hr. This AI provides 80% of the value for $9.99/mo. The personal finance app market is $1.5B. Low price point = high volume potential. 300 users × $9.99 = $2,997/mo.",
    features: [
      { title: "Smart Spending Analysis", description: "AI categorizes transactions and identifies where you're overspending" },
      { title: "Savings Finder Agent", description: "Finds recurring charges, unused subscriptions, and negotiable bills" },
      { title: "Budget Autopilot", description: "AI creates and adjusts budgets based on your income and goals" },
      { title: "Weekly Money Tips", description: "Personalized savings tips and financial insights delivered weekly" },
      { title: "Goal Tracking", description: "Set savings goals and get AI-powered strategies to reach them faster" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "Plaid API", "Supabase", "Resend", "Stripe", "Vercel"],
    keyLearnings: [
      "Plaid API for bank account connectivity",
      "Financial data analysis and pattern recognition",
      "Building trust with sensitive financial data",
      "Subscription retention strategies for consumer apps",
    ],
    ctaText: "Connect Your Bank",
    heroSubtitle: "AI agent that analyzes your spending, finds savings, and coaches you to financial freedom.",
    buildWeek: "Week 33–34",
    idealCustomer: "Millennials and Gen-Z professionals earning $40K-$120K who want to save more but don't know where to start. They're app-native, subscription-friendly, and open to AI managing their finances.",
    competitors: ["Mint (Intuit)", "YNAB", "Copilot Money", "Monarch Money", "Cleo AI"],
    useCases: ["Identifying and canceling unused subscriptions", "Getting weekly spending summaries with saving tips", "Setting and tracking a vacation savings goal", "Finding better rates on recurring bills like insurance"],
  },
  {
    id: "ai-real-estate-agent",
    number: 18,
    title: "AI Real Estate Listing Agent",
    tagline: "Listings that sell, written by AI in seconds",
    description:
      "Upload property photos — the AI agent generates compelling listing descriptions, virtual staging, floor plan analysis, neighborhood insights, and optimized listing copy for Zillow/MLS.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-real-estate-agent",
    type: "PropTech AI",
    status: "upcoming",
    icon: Home,
    pricing: "$29/listing or $99/mo unlimited",
    revenueModel: "Pay-per-use + subscription",
    monthlyRevenuePotential: "$3,000–$10,000",
    whyItMakesMoney: "6M+ homes sold/yr in the US. Agents spend 1-2 hours writing each listing. Professional copywriters charge $100+/listing. At $29/listing with 100 agents doing 2 listings each = $5,800/mo. Subscription for active agents.",
    features: [
      { title: "Photo-to-Description Agent", description: "Analyzes property photos and generates vivid, compelling descriptions" },
      { title: "AI Virtual Staging", description: "Generates virtually staged versions of empty rooms" },
      { title: "Neighborhood Analysis", description: "Auto-researches and includes local schools, restaurants, and transit data" },
      { title: "MLS-Optimized Copy", description: "Formats descriptions to MLS character limits and best practices" },
      { title: "Social Media Kit", description: "Generates Instagram/Facebook ad copy and image overlays" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4 Vision", "DALL-E 3", "Google Maps API", "Supabase", "Stripe", "Vercel"],
    keyLearnings: [
      "Vision models for real estate photo analysis",
      "AI virtual staging and image generation",
      "Real estate industry copy conventions",
      "Geo-data enrichment and neighborhood APIs",
    ],
    ctaText: "Create Your Listing",
    heroSubtitle: "Upload property photos. Get compelling descriptions, virtual staging, and social ads — instantly.",
    buildWeek: "Week 35–36",
    idealCustomer: "Real estate agents listing 5+ properties per month, property management companies, and Airbnb hosts who need compelling descriptions fast. They know great copy sells faster but can't write it themselves.",
    competitors: ["Zillow Premier Agent", "ListingAI", "Epique AI", "Virtual Staging AI", "Restb.ai"],
    useCases: ["Agent generating MLS listing descriptions from phone photos", "Property manager creating Airbnb listing copy", "Developer marketing new construction with AI-staged images", "International agent localizing listings for foreign buyers"],
  },
  {
    id: "ai-newsletter-agent",
    number: 19,
    title: "AI Newsletter Curator Agent",
    tagline: "A newsletter your audience loves — written by AI",
    description:
      "Define your niche — the AI agent scours the internet for the latest news, articles, and trends, curates the best content, writes engaging commentary, and sends a polished newsletter.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-newsletter-agent",
    type: "Media Automation",
    status: "upcoming",
    icon: Newspaper,
    pricing: "$19/mo (weekly newsletter) / $39/mo (daily)",
    revenueModel: "Subscription",
    monthlyRevenuePotential: "$2,000–$6,000",
    whyItMakesMoney: "Newsletter businesses are booming (Substack, Beehiiv). Manual curation takes 5-10 hours/week. This AI does it in minutes. Newsletter operators, marketers, and communities are the market. 100 customers × $25 avg = $2,500/mo.",
    features: [
      { title: "Topic Scanning Agent", description: "Monitors 1000s of sources for your niche — blogs, Twitter/X, Reddit, HN, and more" },
      { title: "Smart Curation", description: "AI selects the most relevant and engaging stories based on your audience" },
      { title: "Commentary Generation", description: "Writes insightful, opinionated commentary in your voice" },
      { title: "Template Design", description: "Beautiful, responsive email templates with your branding" },
      { title: "Auto-Send", description: "Publishes on schedule via Resend, Mailchimp, or Beehiiv" },
    ],
    techStack: ["Next.js", "TypeScript", "LangChain Agents", "OpenAI GPT-4", "RSS Feeds", "Resend", "Supabase", "Stripe", "Cron Jobs"],
    keyLearnings: [
      "Multi-source content aggregation and ranking",
      "AI writing with consistent voice and tone",
      "Email design and deliverability optimization",
      "Building automated publishing pipelines",
    ],
    ctaText: "Launch Your AI Newsletter",
    heroSubtitle: "AI agent that curates, writes, and sends a professional newsletter for your niche — on autopilot.",
    buildWeek: "Week 37–38",
    idealCustomer: "Newsletter operators, community managers, and marketers who want to publish consistently but spend too much time finding and curating content. They need AI to do the research, and they add the human touch.",
    competitors: ["Beehiiv", "Substack", "Curated.co", "Mailbrew", "Stoop"],
    useCases: ["Running a daily AI news newsletter on autopilot", "Curating a weekly industry roundup for a B2B audience", "Auto-generating a community digest from Slack/Discord activity", "Creating a 'best of the web' newsletter for a niche hobby"],
  },
  {
    id: "ai-tutoring-agent",
    number: 20,
    title: "AI Tutoring Agent",
    tagline: "A personal tutor that adapts to how you learn",
    description:
      "An AI tutoring agent that creates personalized learning paths, explains concepts at your level, generates practice problems, and tracks mastery — for any subject.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-tutoring-agent",
    type: "EdTech AI",
    status: "upcoming",
    icon: GraduationCap,
    pricing: "$14.99/mo (student) / $49/mo (family)",
    revenueModel: "Subscription",
    monthlyRevenuePotential: "$3,000–$10,000",
    whyItMakesMoney: "Private tutoring costs $40-100/hr. Parents spend $47B/yr on supplemental education. This AI tutors 24/7 for $14.99/mo. Students K-12 and college are the market. 250 students × $17 avg = $4,250/mo.",
    features: [
      { title: "Adaptive Learning Agent", description: "Adjusts difficulty and teaching style based on student performance" },
      { title: "Multi-Subject Support", description: "Math, science, English, history, coding, and more" },
      { title: "Practice Problem Generator", description: "Creates unlimited practice problems matched to your weak areas" },
      { title: "Step-by-Step Explanations", description: "Breaks down complex problems with visual, step-by-step walkthroughs" },
      { title: "Progress Dashboard", description: "Parents and students track mastery, streaks, and improvement trends" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "LaTeX (math rendering)", "Supabase", "Stripe", "Vercel"],
    keyLearnings: [
      "Adaptive learning algorithms and mastery tracking",
      "Math rendering and visual explanation generation",
      "Building engaging educational UX for students",
      "Spaced repetition and learning science implementation",
    ],
    ctaText: "Start Learning Free",
    heroSubtitle: "AI tutor that adapts to your learning style, generates practice, and tracks your mastery — 24/7.",
    buildWeek: "Week 39–40",
    idealCustomer: "Parents of K-12 students who want supplemental education, college students struggling with specific subjects, and lifelong learners. They value personalized attention but can't afford $50+/hour tutors.",
    competitors: ["Khan Academy", "Chegg", "Photomath", "Brainly", "Khanmigo"],
    useCases: ["High school student getting step-by-step help with calculus", "Parent setting up a personalized learning plan for their 8-year-old", "College student practicing organic chemistry with AI-generated problems", "Adult learner studying for a professional certification exam"],
  },
  {
    id: "ai-review-manager",
    number: 21,
    title: "AI Review Response Agent",
    tagline: "Reply to every review — perfectly, automatically",
    description:
      "An AI agent that monitors your Google, Yelp, Trustpilot, and App Store reviews, crafts thoughtful responses, handles negative reviews with empathy, and alerts you to critical issues.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-review-manager",
    type: "Reputation Management",
    status: "upcoming",
    icon: Star,
    pricing: "$29/mo (1 location) / $79/mo (5 locations)",
    revenueModel: "Per-location subscription",
    monthlyRevenuePotential: "$2,500–$8,000",
    whyItMakesMoney: "89% of consumers read review responses. Businesses lose customers from unanswered reviews. Local businesses, restaurants, and agencies managing multiple locations pay monthly. 80 locations × $40 avg = $3,200/mo.",
    features: [
      { title: "Multi-Platform Monitoring", description: "Tracks reviews across Google, Yelp, Trustpilot, G2, and app stores" },
      { title: "AI Response Generation", description: "Crafts on-brand, empathetic responses tailored to each review's sentiment" },
      { title: "Negative Review Handler", description: "Special care for negative reviews — empathetic, solution-oriented, brand-safe" },
      { title: "Auto-Publish or Approve", description: "Publish responses automatically or send for manager approval" },
      { title: "Sentiment Analytics", description: "Dashboard showing review trends, sentiment shifts, and NPS estimates" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "Google Business API", "Supabase", "Stripe", "Cron Jobs", "Resend"],
    keyLearnings: [
      "Sentiment analysis and response tone calibration",
      "Multi-platform review API integrations",
      "Building approval workflows for automated responses",
      "Reputation management best practices",
    ],
    ctaText: "Manage Your Reviews",
    heroSubtitle: "AI agent that monitors and responds to all your reviews — empathetically, instantly, on brand.",
    buildWeek: "Week 41–42",
    idealCustomer: "Local businesses (restaurants, dental offices, salons), multi-location brands, and reputation management agencies. They get reviews on 3+ platforms and never have time to respond to all of them.",
    competitors: ["Birdeye", "Podium", "Reputation.com", "ReviewTrackers", "Yext"],
    useCases: ["Restaurant responding to 50+ Google reviews per month", "Dental practice addressing negative Yelp reviews empathetically", "Agency managing reviews for 20 client locations", "Hotel chain maintaining consistent response quality across properties"],
  },
  {
    id: "ai-podcast-producer",
    number: 22,
    title: "AI Podcast Producer Agent",
    tagline: "Upload an episode, get everything else done by AI",
    description:
      "Upload a podcast recording — the AI agent transcribes it, generates show notes, creates timestamped chapters, extracts quotable clips, writes social posts, and produces audiograms.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-podcast-producer",
    type: "Creator AI Tool",
    status: "upcoming",
    icon: Mic,
    pricing: "$19/mo (4 episodes) / $39/mo (unlimited)",
    revenueModel: "Subscription",
    monthlyRevenuePotential: "$2,000–$5,000",
    whyItMakesMoney: "4M+ podcasts exist and post-production takes 3-5 hours per episode. This cuts it to 5 minutes. Podcast hosts pay for Descript ($24/mo), Podium ($16/mo), etc. This combines everything. 100 creators × $25 avg = $2,500/mo.",
    features: [
      { title: "AI Transcription", description: "Speaker-attributed transcription with 95%+ accuracy using Whisper" },
      { title: "Show Notes Generator", description: "Structured show notes with key takeaways, links, and resources" },
      { title: "Chapter & Timestamps", description: "Auto-generates podcast chapters with timestamps" },
      { title: "Clip Extraction", description: "AI finds the most viral-worthy moments and creates short clips" },
      { title: "Social Media Kit", description: "Generates Twitter threads, LinkedIn posts, and audiogram videos" },
    ],
    techStack: ["Next.js", "TypeScript", "Whisper API", "OpenAI GPT-4", "FFmpeg", "Supabase", "Stripe", "Bull MQ", "Vercel"],
    keyLearnings: [
      "Audio processing and speaker diarization",
      "AI content extraction and highlight detection",
      "Video/audio clip generation with FFmpeg",
      "Building creator-workflow automation tools",
    ],
    ctaText: "Upload Your Episode",
    heroSubtitle: "Upload a podcast recording. Get transcripts, show notes, clips, and social posts — in minutes.",
    buildWeek: "Week 43–44",
    idealCustomer: "Independent podcasters, podcast networks, and content teams who produce weekly episodes but spend 3-5 hours on post-production per episode. They want to publish faster and repurpose content for growth.",
    competitors: ["Descript", "Podium", "Castmagic", "Riverside.fm", "Capsho"],
    useCases: ["Solo podcaster generating show notes and social clips automatically", "Podcast network processing 10+ episodes per week", "Interview show creating highlight reels for YouTube Shorts", "Corporate podcast team extracting key quotes for internal comms"],
  },
  {
    id: "ai-translation-agent",
    number: 23,
    title: "AI Translation & Localization Agent",
    tagline: "Translate your app, site, or docs — with cultural context",
    description:
      "An AI agent that translates your website, app strings, or documentation into multiple languages while preserving cultural context, tone, and brand voice — not just word-for-word.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-translation-agent",
    type: "Localization AI",
    status: "upcoming",
    icon: Languages,
    pricing: "$0.02/word or $49/mo (50,000 words)",
    revenueModel: "Usage-based + subscription",
    monthlyRevenuePotential: "$2,000–$8,000",
    whyItMakesMoney: "Professional translation costs $0.10-0.30/word. DeepL Pro is $25/mo with limited words. This offers culturally-aware AI translation at $0.02/word with context understanding. SaaS companies going global need this. 80 customers × $40 avg = $3,200/mo.",
    features: [
      { title: "Context-Aware Translation", description: "Understands your product context to translate accurately, not literally" },
      { title: "Brand Voice Consistency", description: "Maintains your tone and messaging across all languages" },
      { title: "Developer-Friendly", description: "Supports JSON, YAML, PO, XLIFF, and other i18n formats" },
      { title: "Glossary & Memory", description: "Learns your terminology and ensures consistency across translations" },
      { title: "Bulk Translation", description: "Upload entire codebases or documentation folders for batch processing" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "DeepL API", "Supabase", "Stripe", "Bull MQ", "Vercel"],
    keyLearnings: [
      "Context-aware machine translation techniques",
      "i18n file format parsing and generation",
      "Translation memory and glossary systems",
      "Building developer-focused localization tools",
    ],
    ctaText: "Translate Your Content",
    heroSubtitle: "AI agent that translates with cultural context — preserving your brand voice across every language.",
    buildWeek: "Week 45–46",
    idealCustomer: "SaaS companies expanding internationally, e-commerce brands selling globally, and content creators who want to reach non-English audiences. They need quality beyond Google Translate but can't afford human translators for everything.",
    competitors: ["DeepL", "Phrase (Memsource)", "Lokalise", "Crowdin", "Smartling"],
    useCases: ["SaaS company localizing their app into 10 languages", "E-commerce brand translating 1,000 product descriptions", "Documentation team maintaining multi-language docs in sync", "Marketing team localizing ad copy with cultural adaptation"],
  },
  {
    id: "ai-workflow-builder",
    number: 24,
    title: "AI Workflow Automation Agent",
    tagline: "Build AI automations in plain English",
    description:
      "Describe what you want automated in plain English — the AI agent builds the workflow, connects your apps (Gmail, Slack, Sheets, CRMs), and runs it on schedule or trigger.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-workflow-builder",
    type: "Automation Platform",
    status: "upcoming",
    icon: Workflow,
    pricing: "$39/mo (10 workflows) / $99/mo (unlimited)",
    revenueModel: "Tiered subscription",
    monthlyRevenuePotential: "$5,000–$20,000",
    whyItMakesMoney: "Zapier charges $20-70/mo for simple automations. This uses AI to BUILD the automation from natural language — no drag-and-drop needed. It's Zapier + AI. Small businesses and ops teams are the market. 80 customers × $55 avg = $4,400/mo.",
    features: [
      { title: "Natural Language Workflows", description: "Describe your automation in plain English — AI builds the entire workflow" },
      { title: "App Connections", description: "Connects Gmail, Slack, Google Sheets, HubSpot, Notion, Airtable, and 50+ apps" },
      { title: "AI Decision Nodes", description: "Add AI logic that makes decisions based on content analysis" },
      { title: "Schedule or Trigger", description: "Run workflows on a schedule, webhook trigger, or email trigger" },
      { title: "Error Handling", description: "AI detects and auto-fixes common workflow errors" },
    ],
    techStack: ["Next.js", "TypeScript", "LangChain Agents", "OpenAI GPT-4", "OAuth 2.0", "Redis", "Bull MQ", "Supabase", "Stripe"],
    keyLearnings: [
      "Building a workflow execution engine from scratch",
      "Natural language to structured workflow compilation",
      "OAuth integration with dozens of SaaS apps",
      "Reliable job scheduling and error recovery",
    ],
    ctaText: "Describe Your Workflow",
    heroSubtitle: "Describe what you want automated in plain English. The AI agent builds and runs it.",
    buildWeek: "Week 47–48",
    idealCustomer: "Operations managers, marketing teams, and small business owners who use 5+ SaaS tools but waste hours on repetitive tasks between them. They want Zapier-level automation but with AI intelligence — described in plain English.",
    competitors: ["Zapier", "Make (Integromat)", "n8n", "Activepieces", "Bardeen"],
    useCases: ["Auto-triaging support emails and creating tasks in Linear", "Syncing CRM data to Google Sheets with AI enrichment", "Monitoring RSS feeds and posting summaries to Slack", "Processing inbound leads from forms and scoring them with AI"],
  },
  {
    id: "ai-changelog-agent",
    number: 25,
    title: "AI Changelog & Release Notes Agent",
    tagline: "Git commits → beautiful changelogs, automatically",
    description:
      "Connect your GitHub repo — the AI agent analyzes commits and PRs, generates human-readable release notes, maintains a public changelog page, and notifies users of updates.",
    imageUrl: "/placeholder.svg",
    projectPageUrl: "/projects/ai-changelog-agent",
    type: "Developer Tool",
    status: "upcoming",
    icon: GitCommit,
    pricing: "$12/mo per repo / $39/mo for 5 repos",
    revenueModel: "Per-repo subscription",
    monthlyRevenuePotential: "$1,500–$5,000",
    whyItMakesMoney: "Most SaaS teams skip changelogs because they're tedious. This automates it completely. Every SaaS product needs release notes. At $12/repo with 150 repos = $1,800/mo. Teams with multiple repos upgrade to $39 plan.",
    features: [
      { title: "Git-to-Changelog Agent", description: "Analyzes commits, PRs, and labels to generate structured release notes" },
      { title: "Human-Readable Summaries", description: "Converts technical commit messages into user-friendly descriptions" },
      { title: "Public Changelog Page", description: "Beautiful, hosted changelog page embeddable on your domain" },
      { title: "User Notifications", description: "Email or in-app notifications when new updates ship" },
      { title: "Feature Voting", description: "Let users vote on roadmap items directly on your changelog page" },
    ],
    techStack: ["Next.js", "TypeScript", "OpenAI GPT-4", "GitHub API", "Supabase", "Resend", "Stripe", "MDX", "Vercel"],
    keyLearnings: [
      "GitHub webhook processing and PR analysis",
      "AI summarization of technical content for non-technical readers",
      "Building embeddable and standalone hosted pages",
      "User notification and changelog subscription systems",
    ],
    ctaText: "Connect Your Repo",
    heroSubtitle: "AI agent that turns your git commits into beautiful, user-friendly changelogs and release notes.",
    buildWeek: "Week 49–50",
    idealCustomer: "SaaS product teams, developer tool companies, and open-source maintainers who ship frequently but never communicate updates well. They want changelogs to write themselves from git activity.",
    competitors: ["Changelogfy", "Beamer", "LaunchNotes", "Canny", "Released.so"],
    useCases: ["SaaS team auto-generating release notes from merged PRs", "Open-source project maintaining a public changelog", "Product team collecting feature votes on a roadmap page", "Engineering team notifying users when bug fixes ship"],
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.id === slug);
}

export function getProjectsByStatus(status: ProjectStatus): Project[] {
  return projects.filter((p) => p.status === status);
}
